package guessmarket.engine.exception;

public enum ErrorCode {
    NO_SYSTEM_LOADED,
    INVALID_FILE_PATH,
    FILE_NOT_FOUND,
    NOT_XML_FILE,
    XML_PARSE_ERROR,
    INVALID_EVENT_DEFINITION,
    DUPLICATE_EVENT_ID,
    INVALID_COMMISSION,
    INVALID_OPTION_COUNT,
    INVALID_LMSR_B,
    UNKNOWN_COMMISSION_TYPE,
    EVENT_NOT_FOUND,
    EVENT_ALREADY_CLOSED,
    INVALID_OPTION_NUMBER,
    INVALID_SHARE_QUANTITY,
    ARITHMETIC_OVERFLOW,
    WRONG_TRADING_METHOD
}
